# Use the base image of node 14
FROM node:16-alpine AS builder

# Create app directory
WORKDIR '/app'

# Install app dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Start the application
CMD [ "npm", "start" ]







